spring:
  application:
   name: lsykk_case_library
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/case_library?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: root
  # redis配置
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      # 上传的单个文件大小限制为5MB以内
      max-file-size: 5MB
      # 总上传的数据大小限制在15MB以内
      max-request-size: 15MB
  elasticsearch:
    ip: 127.0.0.1
    port: 9200
    pool: 5
    repositories:
      enable: true
    cluster:
      name: my-application
  http:
    multipart:
      location: /data/upload_tmp


server:
  # 后端端口配置
  port: 8080


# mybatis-plus配置
  # 打印日志到控制台，
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com.lsykk.caselibrary.dao.mapper/*.xml

  # 标识表名称的前缀
  global-config:
    db-config:
      table-prefix: case_library
